# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/a03s/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/a03s

# Prebuilt Firmware
PRODUCT_COPY_FILES += \
    vendor/samsung/a03s/proprietary/vendor/firmware/AbovCapSense.BIN:$(TARGET_COPY_OUT_VENDOR)/firmware/AbovCapSense.BIN \
    vendor/samsung/a03s/proprietary/vendor/firmware/Himax_firmware_hx83102.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_firmware_hx83102.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/Himax_firmware_hx83112.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_firmware_hx83112.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/Himax_mpfw_hx83102.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_mpfw_hx83102.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/Himax_mpfw_hx83112.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/Himax_mpfw_hx83112.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/WIFI_RAM_CODE_soc1_0_1c_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc1_0_1c_1.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/fs18xx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fs18xx.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/gc7202_hsd_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gc7202_hsd_fw.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/gc7202_hsd_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gc7202_hsd_mp.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/hlt_jadard_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/hlt_jadard_firmware.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/ilitek_fw_ls_panda.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ilitek_fw_ls_panda.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/ilitek_fw_txd_boe.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ilitek_fw_txd_boe.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/mdt_jadard_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mdt_jadard_firmware.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/soc1_0_patch_mcu_1c_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_patch_mcu_1c_1_hdr.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/soc1_0_ram_bt_1c_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_bt_1c_1_hdr.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/soc1_0_ram_mcu_1c_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_mcu_1c_1_hdr.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/soc1_0_ram_wifi_1c_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_wifi_1c_1_hdr.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/txd_hkc_firmware_nl9911c.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txd_hkc_firmware_nl9911c.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/txd_jadard_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txd_jadard_firmware.bin \
    vendor/samsung/a03s/proprietary/vendor/firmware/xl_truly_firmware_nl9911c.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/xl_truly_firmware_nl9911c.bin
